import SideBar from "./sideBar/page";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
        <SideBar/>
        {children}
        </div>
      </body>
    </html>
  );
}
