import Header from "./components/header/page";
import Footer from "./components/footer/page";

import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-[100dvh]">
        <main className="flex-1">
         <Header />
        {children}
        </main>
        <div>
        <Footer/>
        </div>
        </div>
      </body>
    </html>
  );
}
